### ISSUE TITLE
Drupal 9 compatibility?

### ISSUE THREAD

**Issue by wimleers** [dpi/avatars_gravatar#4]
https://www.drupal.org/node/3149707 added Drupal 9 compatibility to https://www.drupal.org/project/avatars 🥳 

Unfortunately https://www.drupal.org/project/avatars_gravatar is not yet compatible. Are there plans to do so? 😊

**Comment by dpi** [comment]
Hey @wimleers, patches welcome.

Archiving this repo and removing the support message from the d.o project. Feel free to open issues back on the d.o queue :)
